upstream backend_cluster {
    server api:8000;
}

server {
    listen 80;

    location / {
        proxy_pass http://backend_cluster;
    }
}

# вам nginx не обязателен, в данный момент пробую себя в DevOps :)
